version: "3.7"
services:
  db:
    image: postgres:14.7-alpine3.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres